export const allDecks = [
  {
    id: 1,
    name: "Creativity",
    deck: [
      {
        name: "Inventive Thought",
        type: "action",
        image: "blank_url",
        effect: "Design a gadget that could make your morning routine easier.",
        category: "Creativity",
        rewardVp: 2,
      },
      {
        name: "Artistic Challenge",
        type: "question",
        image: "blank_url",
        effect:
          "If you could paint anything, what would your masterpiece depict?",
        category: "Creativity",
        rewardVp: 2,
      },
      {
        name: "Creative Solution",
        type: "tip",
        image: "blank_url",
        effect: "Think of a new use for a common household item.",
        category: "Creativity",
        rewardVp: 2,
      },
      {
        name: "Imagination Leap",
        type: "action",
        image: "blank_url",
        effect:
          "Describe a new sport using elements from three existing sports.",
        category: "Creativity",
        rewardVp: 2,
      },
      {
        name: "Innovative Concept",
        type: "question",
        image: "blank_url",
        effect: "If you could invent a new holiday, what would it celebrate?",
        category: "Creativity",
        rewardVp: 2,
      },
    ],
  },
  {
    id: 2,
    name: "Minimalism",
    deck: [
      {
        name: "Simplify Life",
        type: "action",
        image: "blank_url",
        effect: "Identify one thing you can live without and explain why.",
        category: "Minimalism",
        rewardVp: 2,
      },
      {
        name: "Clutter Clear",
        type: "question",
        image: "blank_url",
        effect: "What item do you own that brings you the least joy?",
        category: "Minimalism",
        rewardVp: 2,
      },
      {
        name: "Space Creator",
        type: "tip",
        image: "blank_url",
        effect: "Find a way to organize a small space more efficiently.",
        category: "Minimalism",
        rewardVp: 2,
      },
      {
        name: "Mindful Possession",
        type: "action",
        image: "blank_url",
        effect: "Choose an item to donate that you haven't used in a year.",
        category: "Minimalism",
        rewardVp: 2,
      },
      {
        name: "Essentialism",
        type: "question",
        image: "blank_url",
        effect:
          "What is one thing you use daily that is essential to your happiness?",
        category: "Minimalism",
        rewardVp: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Mindfulness",
    deck: [
      {
        name: "Breath Focus",
        type: "action",
        image: "blank_url",
        effect: "Take a minute to focus solely on your breathing.",
        category: "Mindfulness",
        rewardVp: 2,
      },
      {
        name: "Gratitude Moment",
        type: "question",
        image: "blank_url",
        effect: "Name three things you're grateful for today.",
        category: "Mindfulness",
        rewardVp: 2,
      },
      {
        name: "Present Awareness",
        type: "tip",
        image: "blank_url",
        effect: "Observe your surroundings and note three new details.",
        category: "Mindfulness",
        rewardVp: 2,
      },
      {
        name: "Mindful Eating",
        type: "action",
        image: "blank_url",
        effect: "Eat a meal without any distractions and focus on the flavors.",
        category: "Mindfulness",
        rewardVp: 2,
      },
      {
        name: "Inner Reflection",
        type: "question",
        image: "blank_url",
        effect: "What thought or feeling have you been avoiding lately?",
        category: "Mindfulness",
        rewardVp: 2,
      },
    ],
  },
  {
    id: 4,
    name: "Productivity",
    deck: [
      {
        name: "Task Breakdown",
        type: "action",
        image: "blank_url",
        effect: "Write down the steps to complete an upcoming task.",
        category: "Productivity",
        rewardVp: 2,
      },
      {
        name: "Efficiency Audit",
        type: "question",
        image: "blank_url",
        effect: "What's one thing you could do faster or more efficiently?",
        category: "Productivity",
        rewardVp: 2,
      },
      {
        name: "Goal Setting",
        type: "tip",
        image: "blank_url",
        effect: "Set a small, achievable goal for the day and commit to it.",
        category: "Productivity",
        rewardVp: 2,
      },
      {
        name: "Priority Check",
        type: "action",
        image: "blank_url",
        effect: "List your top three priorities for the week.",
        category: "Productivity",
        rewardVp: 2,
      },
      {
        name: "Time Management",
        type: "question",
        image: "blank_url",
        effect: "What task always takes up more time than it should?",
        category: "Productivity",
        rewardVp: 2,
      },
    ],
  },
  {
    id: 5,
    name: "Health",
    deck: [
      {
        name: "Healthy Choice",
        type: "action",
        image: "blank_url",
        effect: "Swap a usual snack for a healthier option today.",
        category: "Health",
        rewardVp: 2,
      },
      {
        name: "Wellness Reflection",
        type: "question",
        image: "blank_url",
        effect: "What is one healthy habit you are proud of?",
        category: "Health",
        rewardVp: 2,
      },
      {
        name: "Activity Boost",
        type: "tip",
        image: "blank_url",
        effect: "Add a short walk or stretching session to your day.",
        category: "Health",
        rewardVp: 2,
      },
      {
        name: "Nutrition Insight",
        type: "action",
        image: "blank_url",
        effect: "Name a food that is both tasty and healthy.",
        category: "Health",
        rewardVp: 2,
      },
      {
        name: "Self-care Plan",
        type: "question",
        image: "blank_url",
        effect: "What's one thing you can do for your mental health this week?",
        category: "Health",
        rewardVp: 2,
      },
    ],
  },
];
