export const habits = [
  {
    name: "Watch BGGs how to play",
    type: "habit",
    duration: "1h",
    frequency: "trigger",
    description:
      "This is a relaxing activity better than wasting time, because I can learn mechanics about board games while i enjoy and relax before bed time.",
    notes: [],
  },
  {
    name: "Yoga Surya Kriya",
    type: "habit",
    duration: "20 min",
    frequency: "daily",
    notes: [],
  },
  {
    name: "Plan",
    type: "habit",
    duration: "5 min",
    frequency: "daily",
    notes: [],
  },
  {
    name: "GPT Coach",
    type: "habit",
    duration: "30 min",
    frequency: "daily",
    notes: [],
  },
  {
    name: "Water Glasses",
    type: "habit",
    duration: "1 min",
    frequency: "daily",
    notes: [],
  },
  {
    name: "Deep Work Blocks",
    type: "habit",
    duration: "50 min",
    frequency: "daily",
    notes: ["Alone", "Shield Block", "Creativity Projects"],
  },
  {
    name: "Sitting Breaks",
    type: "habit",
    duration: "10 min",
    frequency: "daily",
    notes: [],
  },
  {
    name: "Meditate Clean Mind",
    type: "habit",
    duration: "10 min",
    frequency: "daily",
    notes: [],
  },
  {
    name: "Sport Activity",
    type: "habit",
    duration: "1 - 2 hours",
    frequency: "daily",
    notes: ["tennis", "basket", "gibbon", "bike", "rollerblades"],
  },
  {
    name: "Playing (Inspiration Farm)",
    type: "activity",
    duration: "",
    frequency: "",
    notes: [],
  },
  {
    name: "Creative UX",
    type: "habit",
    duration: "1 h",
    frequency: "daily",
    notes: [],
  },
  {
    name: "Reflecting",
    type: "activity",
    duration: "",
    frequency: "",
    notes: [],
  },
  {
    name: "System Crafting",
    type: "activity",
    duration: "",
    frequency: "",
    notes: [],
  },
  {
    name: "General Tasks",
    type: "activity",
    duration: "",
    frequency: "",
    notes: [],
  },
  {
    name: "AI Research",
    type: "activity",
    duration: "",
    frequency: "",
    notes: [],
  },
  {
    name: "Retreat Mini",
    type: "activity",
    duration: "",
    frequency: "",
    notes: [],
  },
  {
    name: "Shamanic Breathing",
    type: "activity",
    duration: "",
    frequency: "",
    notes: [],
  },
];
