const allCards = [
  {
    id: 1,
    emoji: "🧘",
    title: "Mindful Moments",
    description: "Take a moment to be present.",
    type: "Mindfulness",
    content: "Take five deep breaths, focusing on each inhale and exhale.",
    goldReward: 3,
    goldCost: 0,
  },
  {
    id: 2,
    emoji: "📚",
    title: "Read Daily",
    description: "Expand your mind with daily reading.",
    type: "Learning",
    content: "Read a chapter of a book, or an article on a topic of interest.",
    goldReward: 2,
    goldCost: 3,
  },
  {
    id: 3,
    emoji: "🧘",
    title: "Mindful Moments",
    description: "Take a moment to be present.",
    type: "Mindfulness",
    content: "Take five deep breaths, focusing on each inhale and exhale.",
    goldReward: 3,
    goldCost: 0,
  },
  {
    id: 4,
    emoji: "📚",
    title: "Read Daily",
    description: "Expand your mind with daily reading.",
    type: "Learning",
    content: "Read a chapter of a book, or an article on a topic of interest.",
    goldReward: 2,
    goldCost: 3,
  },
  {
    id: 5,
    emoji: "🧘",
    title: "Mindful Moments",
    description: "Take a moment to be present.",
    type: "Mindfulness",
    content: "Take five deep breaths, focusing on each inhale and exhale.",
    goldReward: 3,
    goldCost: 0,
  },
];

const startingDeck = [
  {
    id: 6,
    emoji: "📚",
    title: "Read Daily",
    description: "Expand your mind with daily reading.",
    type: "Learning",
    content: "Read a chapter of a book, or an article on a topic of interest.",
    goldReward: 2,
    goldCost: 3,
  },
  {
    id: 7,
    emoji: "🧘",
    title: "Mindful Moments",
    description: "Take a moment to be present.",
    type: "Mindfulness",
    content: "Take five deep breaths, focusing on each inhale and exhale.",
    goldReward: 3,
    goldCost: 0,
  },
  {
    id: 8,
    emoji: "📚",
    title: "Read Daily",
    description: "Expand your mind with daily reading.",
    type: "Learning",
    content: "Read a chapter of a book, or an article on a topic of interest.",
    goldReward: 2,
    goldCost: 3,
  },
  {
    id: 9,
    emoji: "📚",
    title: "Read Daily",
    description: "Expand your mind with daily reading.",
    type: "Learning",
    content: "Read a chapter of a book, or an article on a topic of interest.",
    goldReward: 2,
    goldCost: 3,
  },
  {
    id: 10,
    emoji: "🧘",
    title: "Mindful Moments",
    description: "Take a moment to be present.",
    type: "Mindfulness",
    content: "Take five deep breaths, focusing on each inhale and exhale.",
    goldReward: 3,
    goldCost: 0,
  },
  {
    id: 11,
    emoji: "📚",
    title: "Read Daily",
    description: "Expand your mind with daily reading.",
    type: "Learning",
    content: "Read a chapter of a book, or an article on a topic of interest.",
    goldReward: 2,
    goldCost: 3,
  },
];

export const data = { allCards, startingDeck };
